import { createProgressStore } from './progress.js';
import { renderLandscape, renderHiker } from './scene.js';
import { getCourseMapState } from './course-map.js';

const root = document.querySelector('#app');
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const icons = {
 mountain:'<path d="m3 19 7-13 4 7 3-5 5 11H3Z"/><path d="m7 12 3 2 3-2"/>',
 map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Z"/><path d="M9 3v16M15 5v16"/>',
 book:'<path d="M12 5c-4-3-8-2-9-1v15c3-1 6-1 9 1 3-2 6-2 9-1V4c-1-1-5-2-9 1Zm0 0v15"/>',
 arrow:'<path d="M4 12h15m-6-6 6 6-6 6"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 lock:'<rect x="6" y="10" width="12" height="11" rx="3"/><path d="M9 10V6a3 3 0 0 1 6 0v4"/>',
 leaf:'<path d="M20 3C8 2 2 9 5 16c7 5 15-1 15-13Z"/><path d="m4 21 11-12"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',
 back:'<path d="m14 5-7 7 7 7"/>',
 flag:'<path d="M5 22V3c5-4 9 4 15 0v10c-6 4-10-4-15 0"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.book}</svg>`;
let lessons, progress, view='map', active=0, page=0, choice=null, feedback=null;
const motionPreference = window.matchMedia('(prefers-reduced-motion: reduce)');
let motion = !motionPreference.matches;
document.documentElement.classList.toggle('page-hidden',document.hidden);
document.addEventListener('visibilitychange',()=>{document.documentElement.classList.toggle('page-hidden',document.hidden);});
motionPreference.addEventListener('change',event=>{if(event.matches){motion=false;document.querySelector('.app-shell')?.classList.add('still');const button=document.querySelector('[data-action="motion"]');if(button){button.setAttribute('aria-pressed','false');button.querySelector('span').textContent=view==='map'?'움직임 꺼짐':'풍경 움직임 꺼짐';}}});
let resultsUnitId=null, selfModelVisible=false;
const stageLabel=unit=>getCourseMapState(progress.getState()).stages.find(stage=>stage.stage===unit.stage)?.title||`${unit.stage}단계`;
const isSelfCheck=lesson=>lesson.assessment?.type==='selfCheck';
const unitIdOf=lesson=>lesson.unitId||'stage-1-unit-1';
function unitContext(unitId){const state=progress.getState(),course=getCourseMapState(state),unit=course.units.find(item=>item.id===unitId)||course.units[0];const entries=lessons.map((lesson,index)=>({lesson,index})).filter(({lesson})=>unit.lessonIds?unit.lessonIds.includes(lesson.id):unitIdOf(lesson)===unit.id);const done=entries.filter(({lesson})=>state.completedLessonIds.includes(lesson.id)).length;return{unit,entries,done,total:entries.length,complete:entries.length>0&&done===entries.length,course,state};}
function lessonContext(index=active){const context=unitContext(unitIdOf(lessons[index]));return{...context,position:context.entries.findIndex(entry=>entry.index===index)};}
function unitStatusLabel(unit){return unit.status==='completed'?'단원 완료 · 복습 가능':unit.status==='locked'?'이전 단원 완료 후 열림':unit.status==='available'?'학습 가능':'준비 중';}
let sidebarExpanded=false, lastCompleted=-1;

function shell(content) {
 if(view==='map'){mapShell(content);return;}
 const displayUnit=unitContext(view==='results'?resultsUnitId:unitIdOf(lessons[active])).unit;
 root.innerHTML = `<div class="app-shell ${sidebarExpanded?'sidebar-expanded':'sidebar-collapsed'} ${motion?'':'still'}"><aside class="sidebar"><button class="sidebar-toggle" data-action="sidebar" aria-expanded="${sidebarExpanded}" aria-label="${sidebarExpanded?'메뉴 접기':'메뉴 펼치기'}">${icon('map')}<span>${sidebarExpanded?'메뉴 접기':'메뉴'}</span></button><a class="brand" href="#" data-action="map" aria-label="JOHN EDU 학습지도">${icon('mountain')}<span>JOHN EDU<small>배움의 산</small></span></a><div class="sidebar-label">나의 배움</div><nav aria-label="주요 메뉴"><button class="nav-item ${view==='map'?'selected':''}" data-action="map" aria-label="학습 지도" title="학습 지도">${icon('map')}<b>학습 지도</b><span>01</span></button><button class="nav-item ${view==='results'?'selected':''}" data-action="results" aria-label="학습 기록" title="학습 기록">${icon('book')}<b>학습 기록</b></button></nav><div class="journey-box"><div class="mini-mountain">${icon('mountain')}</div><p>작은 배움이 모여<br><strong>더 넓은 세상으로.</strong></p><span>나만의 속도로 올라가세요.</span></div><div class="sidebar-bottom"><div class="avatar">${icon('leaf')}</div><div><strong>오늘의 탐험가</strong><small>${esc(stageLabel(displayUnit))} · ${displayUnit.unitIndex}단원</small></div></div></aside><div class="main-shell"><header class="topbar"><div class="breadcrumb">나의 배움 <span>/</span> <strong>${view==='map'?'학습 지도':view==='results'?'학습 기록':esc(stageLabel(displayUnit))}</strong></div><div class="topbar-actions"><span class="prototype-label">P1 체험판</span><button class="motion-button" data-action="motion" aria-pressed="${motion}" title="풍경 애니메이션 켜기 또는 끄기">${icon('sun')}<span>풍경 움직임 ${motion?'켜짐':'꺼짐'}</span></button></div></header><main id="main-content" tabindex="-1">${content}</main><footer class="app-footer"><span>JOHN EDU · 배움의 산</span><span>체험 진도는 이 브라우저에만 저장됩니다.${progress.getState().storageAvailable===false?' 현재 저장을 사용할 수 없습니다.':''}</span></footer></div></div>`;
 bind();
}
const currentIndex = () => {const index=lessons.findIndex(l=>progress.getLessonStatus(l.id)==='available');return index<0?lessons.length-1:index;};
function mapShell(content) {
 root.innerHTML=`<div class="app-shell world-app ${motion?'':'still'}"><header class="world-topbar"><a class="world-brand" href="#" data-action="map">${icon('mountain')}<strong>JOHN EDU</strong><span>배움의 산</span></a><nav aria-label="지도 조작"><button data-action="results">${icon('book')}<span>나의 학습</span></button><button data-action="current">${icon('map')}<span>현재 위치</span></button><button data-action="motion" aria-pressed="${motion}" title="풍경 움직임"><span>움직임 ${motion?'켜짐':'꺼짐'}</span></button><span class="world-demo">체험판</span></nav></header><main id="main-content" tabindex="-1">${content}</main></div>`;
 bind();
}
function renderMap() {
 view='map'; const state=progress.getState(), course=getCourseMapState(state),current=unitContext(course.currentUnitId),done=current.done,total=current.total,next=current.entries.find(entry=>progress.getLessonStatus(entry.lesson.id)==='available')?.index??current.entries[0]?.index??0,currentMapIndex=course.units.findIndex(unit=>unit.id===current.unit.id);
 // Pixel coordinates traced on the approved 1024 x 1536 cleaned portrait.
 const trail=[[470,1430],[430,1390],[545,1330],[530,1260],[400,1200],[350,1140],[400,1100],[480,1050],[600,980],[565,910],[480,865],[440,830],[525,775],[510,730],[460,690],[470,640],[435,590],[425,550],[550,490],[565,425],[525,370],[535,330],[570,220],[570,165]];
 const lengths=[0];trail.slice(1).forEach((point,i)=>lengths.push(lengths[i]+Math.hypot(point[0]-trail[i][0],point[1]-trail[i][1])));
 const coords=course.units.map((unit,i)=>{const distance=lengths.at(-1)*i/(course.units.length-1);let segment=lengths.findIndex((length,j)=>j>0&&length>=distance);if(segment<1)segment=1;const from=trail[segment-1],to=trail[segment],part=(distance-lengths[segment-1])/(lengths[segment]-lengths[segment-1]);return{x:from[0]+(to[0]-from[0])*part,y:from[1]+(to[1]-from[1])*part};});
 const pathFor=()=>trail.map((point,i)=>`${i?'L':'M'}${point[0]} ${point[1]}`).join(' ');
 const stages=[{number:1,title:'베이스캠프',range:'01—05',first:0},{number:2,title:'숲길',range:'06—09',first:5},{number:3,title:'능선',range:'10—13',first:9},{number:4,title:'고지대',range:'14—17',first:13},{number:5,title:'정상과 그 이후',range:'18—21',first:17}];
 shell(`<section class="world-map-shell" aria-label="배움의 산 전체 교육과정"><div class="world-course-caption"><span>YOUR LEARNING JOURNEY</span><h1>한 걸음씩, 더 넓은 세상으로.</h1><p>5단계 · 21개 단원 · ${course.completedUnitCount}/21개 단원 완료</p></div><div class="map-viewport" tabindex="0" aria-label="전체 학습지도. 위아래로 스크롤하여 21개 단원을 둘러보세요."><div class="map-scene map-canvas world-canvas">${renderLandscape()}<svg class="route world-route portrait-route" viewBox="0 0 1024 1536" preserveAspectRatio="xMidYMid meet" aria-hidden="true"><path d="${pathFor()}"/></svg>${course.units.map((unit,i)=>`<div class="map-stop world-stop unit-${i+1} ${unit.id===course.currentUnitId?'current-unit':''} ${unit.status}" data-theme="${unit.stage}" style="--node-x:${coords[i].x/1024*100}%;--node-y:${coords[i].y/1536*100}%;top:var(--node-y)">${unit.id===course.currentUnitId?`<div class="you-label">현재 위치 · ${unit.unitIndex}단원</div>${renderHiker()}`:''}${unit.isSummit?'<span class="summit-marker">전체 여정의 정상</span>':''}<button class="node" data-unit="${i}" aria-describedby="unit-tooltip-${i}" aria-label="${i+1}단원 ${esc(unit.title)} · ${unitStatusLabel(unit)}">${i+1}${unit.status==='completed'?`<span class="node-completion-badge">${icon('check')}</span>`:''}</button><div class="world-node-label" role="tooltip" id="unit-tooltip-${i}"><span>${icon(unit.status==='completed'?'check':unit.status==='locked'?'lock':unit.id===course.currentUnitId?'flag':'book')}${unit.stage}단계 · ${unitStatusLabel(unit)}</span><strong>${esc(unit.title)}</strong></div></div>`).join('')}</div></div><nav class="world-altitude" aria-label="단계 풍경 미리보기">${stages.slice().reverse().map(stage=>`<button data-stage="${stage.first}" data-theme="${stage.number}" title="${stage.title} 지도 미리보기"><i>${stage.number}</i><span>${stage.title}</span></button>`).join('')}<small>풍경 미리보기</small></nav><aside class="world-continue" aria-label="현재 학습 이어하기"><div class="world-continue-heading"><span>${esc(stageLabel(current.unit))} · ${current.unit.unitIndex}단원</span><strong>${done}/${total}강</strong></div><h2>${current.complete?`${esc(current.unit.title)} · 완료`:esc(lessons[next].title)}</h2><div class="progress-track"><div style="width:${total?Math.round(done/total*100):0}%"></div></div><div class="world-continue-actions"><button class="primary" ${current.complete?`data-result-unit="${current.unit.id}"`:`data-lesson="${next}"`}>${current.complete?'단원 복습':'이어서 학습'}${icon('arrow')}</button><button class="unit-list-button" data-unit="${currentMapIndex}">강의 목록</button></div><p>${course.overallCourseCompleted?'전체 학습 경로 완료 · 정상 도착':current.complete?'단원 학습 완료 · 복습할 수 있습니다':`${current.unit.unitIndex}단원 ${total}강 · 전체 ${course.totalUnits}단원 중 ${course.completedUnitCount}단원 완료`}</p></aside><span class="world-storage">체험 진도는 이 브라우저에 저장${state.storageAvailable?'':'되지 않습니다'}</span></section>`);
 root.querySelectorAll('[data-unit]').forEach(button=>button.addEventListener('click',()=>openUnit(Number(button.dataset.unit),button)));
 root.querySelectorAll('[data-stage]').forEach(button=>button.addEventListener('click',()=>{const stop=document.querySelector(`.unit-${Number(button.dataset.stage)+1}`),vp=document.querySelector('.map-viewport');vp.scrollTo({top:Math.max(0,stop.offsetTop-vp.clientHeight*.5),left:Math.max(0,stop.offsetLeft-vp.clientWidth*.5),behavior:motion?'smooth':'instant'});announce('풍경 미리보기입니다. 학습 진도는 바뀌지 않습니다.');}));
}
function openUnit(index,trigger) {
 const course=getCourseMapState(progress.getState()),unit=course.units[index],context=unitContext(unit.id);
 document.querySelector('.unit-dialog-backdrop')?.remove();
 const backdrop=document.createElement('div');backdrop.className='unit-dialog-backdrop';backdrop.innerHTML=`<section class="unit-dialog" role="dialog" aria-modal="true" aria-labelledby="unit-dialog-title"><button class="unit-close" aria-label="단원 안내 닫기">×</button><p class="eyebrow">STAGE ${unit.stage} · UNIT ${String(index+1).padStart(2,'0')}</p><h2 id="unit-dialog-title">${esc(unit.title)}</h2>${context.total?`<p>${unit.unitIndex}단원 · ${context.total}강. ${unit.status==='locked'?'이전 단원을 완료하면 학습할 수 있습니다.':'아래 강의를 순서대로 학습합니다.'}</p><div class="unit-lessons">${context.entries.map(({lesson,index:lessonIndex},i)=>`<button data-unit-lesson="${lessonIndex}" aria-disabled="${progress.getLessonStatus(lesson.id)==='locked'}"><span>${progress.getLessonStatus(lesson.id)==='completed'?'✓':String(i+1).padStart(2,'0')}</span><strong>${esc(lesson.title)}</strong><small>${progress.getLessonStatus(lesson.id)==='completed'?'복습':progress.getLessonStatus(lesson.id)==='locked'?'선행 학습 후':'학습하기'}</small></button>`).join('')}</div>`:`<div class="unit-preparing">${icon('book')}<strong>학습 화면 준비 중</strong><p>이 단원의 교육 원고는 준비되어 있습니다. 학습 화면과 평가를 연결한 뒤 공개합니다. 지도 미리보기로 진도나 수료가 변경되지는 않습니다.</p></div>`}<p class="unit-scope">본과정은 21개 단원입니다. 개별 단원 완료와 단계 완료, 전체 학습 경로 완료는 구분됩니다.</p></section>`;
 root.append(backdrop);const close=()=>{backdrop.remove();trigger?.focus({preventScroll:true});};backdrop.querySelector('.unit-close').addEventListener('click',close);backdrop.addEventListener('click',event=>{if(event.target===backdrop)close();});backdrop.querySelectorAll('[data-unit-lesson]').forEach(button=>button.addEventListener('click',()=>openLesson(Number(button.dataset.unitLesson))));backdrop.addEventListener('keydown',event=>{if(event.key==='Escape')close();if(event.key==='Tab'){const all=[...backdrop.querySelectorAll('button')],first=all[0],last=all.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}});backdrop.querySelector('.unit-close').focus();
}

function inlineText(value){const input=String(value??''),pattern=/(`[^`]+`)|(\[([^\]]+)\]\((https?:\/\/[^\s)]+)\))|(\*\*([^*]+)\*\*)/gi;let output='',cursor=0;for(const match of input.matchAll(pattern)){output+=esc(input.slice(cursor,match.index));if(match[1])output+=`<code>${esc(match[1].slice(1,-1))}</code>`;else if(match[2]){let valid=false;try{valid=['http:','https:'].includes(new URL(match[4]).protocol);}catch{}output+=valid?`<a href="${esc(match[4])}" target="_blank" rel="noopener noreferrer">${esc(match[3])}</a>`:esc(match[3]);}else output+=`<strong>${esc(match[6])}</strong>`;cursor=match.index+match[0].length;}return output+esc(input.slice(cursor));}

function renderFlow(code){const labels={};for(const match of code.matchAll(/([A-Za-z][A-Za-z0-9_]*)[\[{]\"([^\"]+)\"[\]}]/g))labels[match[1]]=match[2];const edges=code.split(/\r?\n/).filter(line=>line.includes('-->')).map(line=>{const compact=line.replace(/([A-Za-z][A-Za-z0-9_]*)[\[{]\"[^\"]+\"[\]}]/g,'$1').trim();const match=compact.match(/^([A-Za-z][A-Za-z0-9_]*)\s*-->\s*(?:\|\"?([^|\"]+)\"?\|\s*)?([A-Za-z][A-Za-z0-9_]*)$/);return match?`<li><span>${esc(labels[match[1]]||match[1])}</span><b>${match[2]?esc(match[2])+' →':'→'}</b><span>${esc(labels[match[3]]||match[3])}</span></li>`:'';}).join('');return `<ol class="learning-flow" aria-label="재검토 흐름과 분기">${edges}</ol>`;}
function richText(value){const source=String(value??'');if(/```mermaid\s*[\s\S]*?```/.test(source)){return source.split(/```mermaid\s*([\s\S]*?)```/g).map((part,index)=>index%2?renderFlow(part):richText(part)).join('');}if(/```[^\n]*\n[\s\S]*?```/.test(source))return source.split(/```[^\n]*\n([\s\S]*?)```/g).map((part,index)=>index%2?`<pre class="lesson-code"><code>${esc(part)}</code></pre>`:richText(part)).join('');const lines=source.split(/\r?\n/),out=[];let plain=[];const flush=()=>{if(plain.length){out.push(`<p>${plain.map(inlineText).join('<br>')}</p>`);plain=[];}};for(let i=0;i<lines.length;i++){const line=lines[i];if(/^\s*\|/.test(line)){flush();const rows=[];while(i<lines.length&&/^\s*\|/.test(lines[i])){rows.push(lines[i].trim().replace(/^\||\|$/g,'').split('|').map(cell=>cell.trim()));i++;}i--;const hasHeader=rows.length>1&&rows[1].every(cell=>/^:?-{2,}:?$/.test(cell));const header=hasHeader?rows.shift():null;if(hasHeader)rows.shift();const columns=Math.max(header?.length||0,...rows.map(row=>row.length));out.push(`${columns>3?'<p class="table-scroll-hint">표를 좌우로 움직여 나머지 열을 확인하세요.</p>':''}<div class="table-scroll" data-columns="${columns}" tabindex="0" role="region" aria-label="학습 자료 표"><table>${header?`<thead><tr>${header.map(cell=>`<th scope="col">${inlineText(cell)}</th>`).join('')}</tr></thead>`:''}<tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td${/^[\d\s,.%()+−-]+$/.test(cell)?' class="numeric-cell"':''}>${inlineText(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`);}else if(/^\s*(?:[-*+] |\d+[.)] )/.test(line)){flush();const ordered=/^\s*\d+[.)] /.test(line),items=[];while(i<lines.length&&(ordered?/^\s*\d+[.)] /:/^\s*[-*+] /).test(lines[i])){items.push(lines[i].replace(/^\s*(?:[-*+] |\d+[.)] )/,''));i++;}i--;out.push(`<${ordered?'ol':'ul'}>${items.map(item=>`<li>${inlineText(item)}</li>`).join('')}</${ordered?'ol':'ul'}>`);}else if(/^#{1,6}\s/.test(line)){flush();out.push(`<h3>${inlineText(line.replace(/^#{1,6}\s+/,''))}</h3>`);}else if(!line.trim()){flush();}else{plain.push(line);}}flush();return out.join('');}
function lessonPages(l) {
 const groups=[];let group=[],size=0;for(const paragraph of l.paragraphs){if(group.length&&!/^#{1,6}\s/.test(group.at(-1).trim())&&(size+paragraph.length>1800||group.length>=4)){groups.push(group);group=[];size=0;}group.push(paragraph);size+=paragraph.length;}if(group.length)groups.push(group);
 return [...groups.map((paragraphs,i)=>({kind:'concept',label:groups.length>1?`개념 ${i+1}/${groups.length}`:'개념 이해',title:l.title,body:`${i===0?`<p class="opening-question">${esc(l.question)}</p>`:''}${paragraphs.map(richText).join('')}`})),{kind:'example',label:'사례와 자료',title:'사례로 연결해 볼까요?',body:`${exampleVisual(l)}${lessonNotices(l)}<div class="example-content">${richText(l.example)}</div>`},{kind:'takeaway',label:'핵심 한 문장',title:'이것만은 기억해 주세요.',body:`<blockquote>${inlineText(l.takeaway)}</blockquote><p class="muted">${isSelfCheck(l)?'다음은 확인 활동입니다. 먼저 생각해 보고 해설과 비교하며 스스로 점검합니다.':'다음은 배운 내용을 확인하는 문제입니다. 틀려도 괜찮아요. 해설을 읽고 다시 도전할 수 있습니다.'}</p>${sourceDetails(l)}`}];
}
function lessonNotices(lesson){const base=lesson.tableContext||(lesson.visual?.unit?`단위: ${lesson.visual.unit}`:''),extra=lesson.tableContext&&lesson.visual?.derivedFromTable?(lesson.visual.note||'').split(/(?<=[.!?])\s+/).filter(sentence=>sentence&&!base.includes(sentence)).join(' '):'',note=[base,extra].filter(Boolean).join(' '),verification=lesson.source?.verification;return `${note?`<p class="table-context-note">${esc(note)}</p>`:''}${lesson.source?.manuscriptDate?`<p class="source-date">원고 기준일: ${esc(lesson.source.manuscriptDate)}</p>`:''}${verification?.checkedAt?`<p class="source-date">출처 확인일: ${esc(verification.checkedAt)}<br>확인 범위: ${esc(verification.scope||'')}</p>`:''}`;}

function sourceDetails(lesson){if(!lesson.source)return '';const refs=[...(lesson.source.references||[]),...(lesson.source.verification?.urls||[]).map((url,index)=>({title:`추가 확인 근거 ${index+1}`,url}))];return `<details class="source-details"><summary>학습 원고와 참고 출처</summary>${lessonNotices(lesson)}<p>${esc(lesson.source.section||lesson.title)}</p>${refs.map(ref=>/^https?:\/\//.test(ref.url||'')?`<p><a href="${esc(ref.url)}" target="_blank" rel="noopener noreferrer">${esc(ref.title||ref.url)}</a></p>`:`<p>${esc(ref.title||'')}</p>`).join('')}</details>`;}

function exampleVisual(l) {
 if(l.visual?.derivedFromTable){return l.visual.note&&!l.tableContext?`<p class="visual-note">${esc(l.visual.note)}</p>`:'';}
 const card=(label,value,note)=>`<div class="concept-card"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`;
 if(l.visual?.type==='cards'&&Array.isArray(l.visual.cards)){return `<div class="concept-visual"><div class="concept-grid ${l.visual.cards.length===3?'three':''}">${l.visual.cards.map(item=>card(esc(item.label),esc(item.value),esc(item.note))).join('')}</div>${l.visual.note?`<p class="visual-note">${esc(l.visual.note)}</p>`:''}</div>`;}
 const views={
  'lesson-1':`<div class="concept-grid">${card('가람 · 비상자금 450만 원','약 3개월','월 필수생활비 150만 원')}${card('나래 · 비상자금 0원','별도 자금 마련 필요','지출 조정 · 지원제도 · 자금 마련 검토')}</div><p class="visual-note">학습용 가상 사례 · 별도의 부채와 수입은 없다고 가정합니다.</p>`,
  'lesson-2':`<div class="concept-grid three">${card('01','교환의 매개','물건과 서비스를 교환하는 수단')}${card('02','가치의 척도','가격을 비교하는 기준')}${card('03','가치의 저장','받은 돈 일부를 나중에 사용')}</div><div class="purchasing-power"><span>같은 1만 원</span><strong>5천 원 × 두 끼</strong><span>→</span><strong>1만 원 × 한 끼</strong></div><p class="visual-note">가상 사례 · 개별 가격 변화의 예시이며 전체 물가상승률을 뜻하지 않습니다.</p>`,
  'lesson-3':`<div class="asset-visual"><div><strong>가람 · 총자산 6,000만 원</strong><div class="asset-bar"><span style="width:75%">부채 4,500만</span><i style="width:25%">순자산 1,500만</i></div></div><div><strong>나래 · 총자산 6,000만 원</strong><div class="asset-bar"><i style="width:100%">순자산 6,000만 · 부채 0원</i></div></div></div><p class="visual-note">학습용 가상 사례 · 순자산 = 총자산 − 총부채. 소비의 옳고 그름을 평가하는 비교가 아닙니다.</p>`,
  'lesson-4':`<div class="concept-grid">${card('노동소득','일에서 얻는 소득','생활과 자산 형성의 중요한 출발점')}${card('자본소득','자산에서 얻는 소득','수익 변동·원금 손실·비용을 함께 확인')}</div><div class="purchasing-power"><strong>1,000만 원 × 연 3%</strong><span>=</span><strong>연 30만 원</strong></div><p class="visual-note">가상 예금 사례 · 1년 단리 · 세전 · 조건 유지 가정. 현재 상품 추천이나 시중금리가 아닙니다.</p>`,
  'lesson-5':`<div class="concept-grid four">${card('가입 전 질문 01','손실 가능성','원금 손실이 생기는 경우는?')}${card('가입 전 질문 02','총비용','수수료와 해지 비용은?')}${card('가입 전 질문 03','인출 조건','필요할 때 꺼낼 수 있나요?')}${card('가입 전 질문 04','나의 목적','내 상황과 목표에 맞나요?')}</div>`
 };
 return `<div class="concept-visual">${views[l.id]||''}</div>`;
}
function renderLesson() {
 view='lesson'; const l=lessons[active], pages=lessonPages(l), p=pages[page],context=lessonContext();
 shell(`<section class="learning-wrap"><button class="text-button" data-action="map">${icon('back')}학습 지도로 돌아가기</button><div class="lesson-heading"><div><p class="eyebrow">${esc(stageLabel(context.unit))} · ${context.unit.unitIndex}단원 · LESSON ${context.position+1}/${context.total}</p><h1>${esc(l.title)}</h1></div><span class="lesson-counter">${page+1} <span>/ ${pages.length}</span></span></div><div class="learning-steps">${pages.map((v,i)=>`<span class="${i===page?'current':i<page?'passed':''}"><i>${i<page?'✓':i+1}</i>${v.label}</span>`).join('')}<span><i>${pages.length+1}</i>${isSelfCheck(l)?'확인 활동':'확인 문제'}</span></div><article class="lesson-paper ${p.kind}"><div class="paper-topline"><span>${p.label}</span><span>JOHN EDU</span></div><h2>${esc(p.title)}</h2>${l.unitContext?`<details class="unit-context"><summary>이 단원의 공통 가정과 범위</summary>${richText(l.unitContext)}</details>`:''}<div class="lesson-copy">${p.body}</div><div class="paper-bottom">배움의 산 <span>${context.unit.unitIndex}단원 — ${context.position+1}강</span></div></article><div class="lesson-controls"><button class="secondary" data-action="previous" ${page===0?'disabled':''}>${icon('back')}이전</button><span>내용을 확인한 뒤 다음으로 이동해 주세요.</span><button class="primary" data-action="next">${page===pages.length-1?(isSelfCheck(l)?'확인 활동 시작':'확인 문제 풀기'):'다음으로'}${icon('arrow')}</button></div></section>`);
}
function renderQuiz() {
 view='quiz';const l=lessons[active],context=lessonContext(),nextEntry=context.entries[context.position+1];if(isSelfCheck(l)){renderSelfCheck();return;}
 shell(`<section class="learning-wrap quiz-wrap"><button class="text-button" data-action="concept">${icon('back')}개념 다시 보기</button><div class="lesson-heading"><div><p class="eyebrow">CHECK YOUR UNDERSTANDING</p><h1>한 걸음, 확인해 볼까요?</h1></div><span class="quiz-number">Q${context.position+1}</span></div><article class="lesson-paper quiz-paper"><div class="paper-topline"><span>${esc(l.title)}</span><span>확인 문제</span></div><h2>${esc(l.quiz.question)}</h2><fieldset ${feedback?'disabled':''}><legend class="sr-only">정답을 하나 선택해 주세요.</legend>${l.quiz.options.map((option,i)=>`<label class="answer-option ${choice===option.id?'chosen':''} ${feedback&&option.id===l.quiz.correctOptionId?'correct-option':''}"><input type="radio" name="answer" value="${esc(option.id)}" ${choice===option.id?'checked':''}/><span class="option-marker">${i+1}</span><span>${esc(option.text)}</span>${feedback&&option.id===l.quiz.correctOptionId?'<span class="correct-badge">정답</span>':choice===option.id?icon('check'):''}</label>`).join('')}</fieldset>${feedback?`${feedback.correct&&!feedback.alreadyCompleted?`<div class="step-celebration"><span>${icon('check')} 한 걸음 더 올라왔어요</span><strong>${context.position+1}강 ✓ <i>→</i> ${nextEntry?esc(nextEntry.lesson.title):`${context.unit.unitIndex}단원 학습 완료`}</strong></div>`:''}<div class="answer-feedback ${feedback.correct?'is-correct':'is-wrong'}" role="status"><strong>${feedback.correct?'잘 이해하셨어요. 한 걸음 완료!':'괜찮아요. 함께 다시 살펴봐요.'}</strong><p>${esc(l.quiz.explanation)}</p>${feedback.showExtraExample?`<div class="extra-help"><strong>사례로 한 번 더</strong><p>${esc(l.extraHelp || l.example)}</p></div>`:''}<span>${feedback.correct&&feedback.attemptCount>1?'복습 후 완료 · 첫 응답과 재시도 기록은 유지됩니다.':'오답에 벌점은 없습니다. 나의 속도로 배워 보세요.'}</span></div>`:''}</article><div class="lesson-controls"><span>${feedback?'해설을 확인하고 다음 걸음을 이어가세요.':'답을 선택하면 제출할 수 있어요.'}</span>${feedback?feedback.correct?`<button class="primary" data-action="finish">${nextEntry?'다음 강의로':'단원 결과 보기'}${icon('arrow')}</button>`:`<button class="primary" data-action="retry">다시 풀기${icon('arrow')}</button>`:`<button class="primary" data-action="submit" ${choice===null?'disabled':''}>답 제출하기${icon('arrow')}</button>`}</div></section>`);
}
function renderSelfCheck(){
 const lesson=lessons[active],context=lessonContext(),nextEntry=context.entries[context.position+1];
 shell(`<section class="learning-wrap quiz-wrap"><button class="text-button" data-action="concept">${icon('back')}개념 다시 보기</button><div class="lesson-heading"><div><p class="eyebrow">REFLECT AND CHECK</p><h1>내 생각을 해설과 비교해 볼까요?</h1></div><span class="quiz-number">${context.position+1}</span></div><article class="lesson-paper self-check-paper"><div class="paper-topline"><span>${esc(lesson.title)}</span><span>확인 활동 · 자기점검</span></div><div class="lesson-copy">${richText(lesson.assessment.prompt)}</div><p class="self-check-note">먼저 스스로 생각하거나 개인 노트에 정리해 보세요. 이 화면에서는 답변을 입력하거나 저장하지 않습니다.</p>${selfModelVisible?`<section class="self-check-model"><h2>해설과 모범답안</h2><div class="lesson-copy">${richText(lesson.assessment.modelAnswer)}</div></section>`:''}${feedback?.completed?`<div class="answer-feedback" role="status"><strong>확인 활동을 마쳤습니다.</strong><p>해설과 비교한 자기점검 기록입니다. 자동 채점이나 이해도 검증을 뜻하지 않습니다.</p>${feedback.alreadyCompleted?'<span>이전 완료 기록을 유지합니다.</span>':''}</div>`:''}</article><div class="lesson-controls"><span>${selfModelVisible?'내 생각과 해설을 비교한 뒤 확인해 주세요.':'먼저 생각해 본 뒤 해설을 열어 주세요.'}</span>${feedback?.completed?`<button class="primary" data-action="finish">${nextEntry?'다음 강의로':'단원 결과 보기'}${icon('arrow')}</button>`:selfModelVisible?'<button class="primary" data-action="self-confirm">해설과 비교해 확인했습니다</button>':'<button class="primary" data-action="self-model">해설 보기</button>'}</div></section>`);
}
function renderResults(unitId) {
 resultsUnitId=unitId||resultsUnitId||getCourseMapState(progress.getState()).currentUnitId;
 view='results';const context=unitContext(resultsUnitId),{state,course,unit,entries,done,total,complete}=context;
 const unitIndex=course.units.findIndex(item=>item.id===unit.id),nextUnit=course.units[unitIndex+1],nextContext=nextUnit?unitContext(nextUnit.id):null;
 const nextReady=nextUnit&&['available','completed'].includes(nextUnit.status);
 const nextEntry=nextContext?.entries.find(entry=>progress.getLessonStatus(entry.lesson.id)==='available')||nextContext?.entries[0];
 const practice=entries.find(({lesson})=>lesson.unitPractice)?.lesson.unitPractice||(unit.id==='stage-1-unit-1'?'앞으로 돈과 관련된 중요한 결정을 하기 전에, 내 목적·총비용·잘못될 가능성을 한 번씩 확인해 보세요.':'');
 shell(`<section class="results-wrap"><p class="eyebrow">EVERY STEP COUNTS</p><div class="result-unit-picker"><label for="result-unit-select">단계와 단원 선택</label><select id="result-unit-select">${course.stages.map(stage=>`<optgroup label="${esc(stage.title)}">${course.units.filter(item=>item.stage===stage.stage&&unitContext(item.id).total>0).map(item=>`<option value="${item.id}" ${item.id===unit.id?'selected':''}>${item.unitIndex}단원 · ${esc(item.title)}</option>`).join('')}</optgroup>`).join('')}</select></div><div class="result-emblem">${icon(complete?'flag':'mountain')}</div><h1>${complete&&unit.isSummit&&course.overallCourseCompleted?'전체 학습 경로를 마쳤어요.':complete?`${stageLabel(unit)} ${unit.unitIndex}단원을 마쳤어요.`:'한 걸음씩 쌓이는 나의 배움'}</h1><p>${esc(stageLabel(unit))} · ${unit.unitIndex}단원 · ${esc(unit.title)}</p><div class="result-stat"><strong>${done}</strong><span>/ ${total}강 완료</span></div><p class="completion-note">${course.overallCourseCompleted?'모든 단원의 학습 경로를 완료했습니다. 이 브라우저의 학습 기록이며 공식 수료증 발급은 별도입니다.':complete?'이 단원의 학습 완료 기록입니다. 남은 단원을 차례로 학습해 보세요.':'완료한 강의는 언제든 다시 학습할 수 있습니다.'}<br>전체 ${course.totalUnits}단원 중 ${course.completedUnitCount}단원 완료</p><div class="result-list">${entries.map(({lesson:l,index})=>`<button data-lesson="${index}" ${progress.getLessonStatus(l.id)==='locked'?'aria-disabled="true"':''}><span class="result-icon ${state.completedLessonIds.includes(l.id)?'done':''}">${icon(state.completedLessonIds.includes(l.id)?'check':progress.getLessonStatus(l.id)==='locked'?'lock':'book')}</span><span><strong>${esc(l.title)}</strong><small>${state.completedLessonIds.includes(l.id)?esc(l.takeaway):'한 걸음씩 순서대로 학습해 보세요.'}</small></span><span>${state.completedLessonIds.includes(l.id)?'복습':progress.getLessonStatus(l.id)==='available'?'학습하기':'잠김'}</span></button>`).join('')}</div>${complete&&nextUnit?`<div class="next-landscape"><span>다음 학습 · ${esc(stageLabel(nextUnit))}</span><h2>${nextUnit.unitIndex}단원 · ${esc(nextUnit.title)}</h2><p>${nextUnit.status==='completed'?'이미 완료한 다음 단원을 다시 복습할 수 있습니다.':nextReady?'다음 단원에서 배움을 이어가세요.':'학습 화면 준비 중'}</p>${nextReady&&nextEntry?`<button class="primary" data-lesson="${nextEntry.index}">${nextUnit.status==='completed'?'다음 단원 복습하기':'다음 단원 시작하기'}${icon('arrow')}</button>`:''}<p>${course.overallCourseCompleted?'전체 학습 경로를 완료한 뒤 복습 중입니다.':'현재 완료는 개별 단원에 대한 기록입니다. 남은 단원을 이어서 학습해 보세요.'}</p></div>`:''}<button class="primary" data-action="map">학습 지도로 돌아가기${icon('arrow')}</button><button class="reset-button" data-action="reset">이 브라우저의 체험 진도 초기화</button><p class="demo-notice">체험판에는 실제 로그인·결제·수료증 발급이 연결되어 있지 않습니다.</p></section>`);
 const resultList=document.querySelector('.result-list');
 if(complete){const metadata=entries.find(({lesson})=>lesson.unitReview?.length||lesson.unitConclusion)?.lesson;if(metadata){const summary=document.createElement('details');summary.className='unit-summary';summary.innerHTML=`<summary>단원 전체 정리</summary>${metadata.unitReview?.length?`<ol>${metadata.unitReview.map(item=>`<li>${inlineText(item)}</li>`).join('')}</ol>`:''}${metadata.unitConclusion?richText(metadata.unitConclusion):''}`;resultList.after(summary);}}
 if(complete&&unit.isSummit&&course.overallCourseCompleted){const summit=document.createElement('section');summit.className='summit-completion';summit.innerHTML=`${icon('flag')}<h2>배움의 산, 정상에 도착했습니다.</h2><p>${course.totalUnits}개 단원의 학습 경로를 모두 완료했습니다. 객관식 확인과 자기점검 활동을 마친 기록이며, 실제 금융 판단의 정확성을 보장하는 평가는 아닙니다.</p>`;resultList.after(summit);}
 entries.forEach(({lesson},index)=>{const attempts=state.attempts[lesson.id]||[];if(state.completedLessonIds.includes(lesson.id))resultList.children[index].lastElementChild.textContent=isSelfCheck(lesson)?'자기점검 완료':attempts[0]?.correct?'첫 시도 완료':'복습 후 완료';});
 if(complete&&practice){const practiceCard=document.createElement('details');practiceCard.className='practice-card practice-details';practiceCard.innerHTML=`<summary>단원 종합 활동 · 생각해 보기</summary><div>${richText(practice)}</div>`;resultList.after(practiceCard);}
 const reviewLessons=entries.filter(({lesson})=>!isSelfCheck(lesson)&&(state.attempts[lesson.id]||[]).some(attempt=>!attempt.correct));
 if(reviewLessons.length){const review=document.createElement('section');review.className='review-card';review.innerHTML=`<h2>한 번 더 돌아볼 개념</h2><p>이 단원에서 처음 어려웠던 개념을 다시 읽어 보세요. 재시도 기록은 처음의 응답과 함께 남습니다.</p>${reviewLessons.map(({lesson,index})=>`<button data-review="${index}">${esc(lesson.title)}${icon('arrow')}</button>`).join('')}`;resultList.after(review);review.querySelectorAll('[data-review]').forEach(button=>button.addEventListener('click',()=>openLesson(Number(button.dataset.review))));}
}

function render() {if(view==='map')renderMap();else if(view==='lesson')renderLesson();else if(view==='quiz')renderQuiz();else renderResults();}
function focusMain(){document.querySelector('#main-content')?.focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});if(view==='map')revealCurrent();}
function revealCurrent(){requestAnimationFrame(()=>{const node=document.querySelector('.current-unit');const viewport=document.querySelector('.map-viewport');if(node&&viewport){viewport.scrollTop=Math.max(0,node.offsetTop-viewport.clientHeight*.52);viewport.scrollLeft=Math.max(0,node.offsetLeft-viewport.clientWidth*.5);}});}
function openLesson(index) {if(progress.getLessonStatus(lessons[index].id)==='locked'){announce('이전 강의를 완료하면 열립니다.');return;}active=index;page=0;choice=null;feedback=null;selfModelVisible=false;renderLesson();focusMain();}
function announce(message){let el=document.querySelector('#notice');if(!el){el=document.createElement('div');el.id='notice';el.className='toast';el.setAttribute('role','status');document.body.append(el);}el.textContent=message;clearTimeout(announce.timer);announce.timer=setTimeout(()=>el.remove(),3500);}
function bind() {
 if(view==='map')revealCurrent();
 root.querySelector('#result-unit-select')?.addEventListener('change',event=>{renderResults(event.target.value);focusMain();});
 root.querySelectorAll('[data-result-unit]').forEach(el=>el.addEventListener('click',()=>{renderResults(el.dataset.resultUnit);focusMain();}));
 root.querySelectorAll('[data-lesson]').forEach(el=>el.addEventListener('click',()=>openLesson(Number(el.dataset.lesson))));
 root.querySelectorAll('input[name="answer"]').forEach(el=>el.addEventListener('change',()=>{choice=el.value;root.querySelectorAll('.answer-option').forEach(option=>option.classList.toggle('chosen',option.querySelector('input').checked));root.querySelector('[data-action="submit"]').disabled=false;}));
 root.querySelectorAll('[data-action]').forEach(el=>el.addEventListener('click',event=>{event.preventDefault();const action=el.dataset.action;
  if(action==='sidebar'){sidebarExpanded=!sidebarExpanded;document.querySelector('.app-shell').classList.toggle('sidebar-expanded',sidebarExpanded);document.querySelector('.app-shell').classList.toggle('sidebar-collapsed',!sidebarExpanded);el.setAttribute('aria-expanded',String(sidebarExpanded));el.setAttribute('aria-label',sidebarExpanded?'메뉴 접기':'메뉴 펼치기');el.querySelector('span').textContent=sidebarExpanded?'메뉴 접기':'메뉴';return;}
  if(action==='motion'){if(motionPreference.matches){announce('기기의 동작 줄이기 설정이 적용되어 있습니다.');return;}motion=!motion;document.querySelector('.app-shell').classList.toggle('still',!motion);el.setAttribute('aria-pressed',String(motion));el.querySelector('span').textContent=`${view==='map'?'움직임':'풍경 움직임'} ${motion?'켜짐':'꺼짐'}`;return;}
  if(action==='current'){revealCurrent();return;}
  if(action==='map')renderMap();if(action==='results')renderResults(view==='map'?getCourseMapState(progress.getState()).currentUnitId:view==='results'?resultsUnitId:unitIdOf(lessons[active]));
  if(action==='next'){if(page<lessonPages(lessons[active]).length-1){page++;renderLesson();}else{choice=null;feedback=null;selfModelVisible=false;renderQuiz();}}
  if(action==='previous'&&page>0){page--;renderLesson();}
  if(action==='concept'){page=0;renderLesson();}
  if(action==='submit'&&choice!==null&&!feedback){el.disabled=true;try{feedback=progress.submitAnswer(lessons[active].id,choice);if(feedback.correct&&!feedback.alreadyCompleted)lastCompleted=active;renderQuiz();}catch(error){el.disabled=false;announce('제출을 처리하지 못했습니다. 다시 시도해 주세요.');return;}}
  if(action==='retry'){choice=null;feedback=null;renderQuiz();}
  if(action==='self-model'&&isSelfCheck(lessons[active])){selfModelVisible=true;renderQuiz();}
  if(action==='self-confirm'&&isSelfCheck(lessons[active])&&selfModelVisible&&!feedback){el.disabled=true;try{feedback=progress.submitSelfCheck(lessons[active].id);renderQuiz();}catch(error){el.disabled=false;announce('자기점검 기록을 저장하지 못했습니다. 다시 시도해 주세요.');return;}}
  if(action==='finish'){const context=lessonContext(),next=context.entries[context.position+1];if(next){openLesson(next.index);return;}renderResults(context.unit.id);}
  if(action==='reset'){
   if(document.querySelector('.reset-confirmation'))return;
   const panel=document.createElement('section');panel.className='reset-confirmation';panel.setAttribute('aria-labelledby','reset-confirm-title');
   panel.innerHTML='<h2 id="reset-confirm-title">체험 진도를 초기화할까요?</h2><p>이 브라우저의 답변과 완료 기록이 지워집니다. 다른 설정은 그대로 유지됩니다.</p><div><button class="secondary" data-reset-cancel>취소</button><button class="primary" data-reset-confirm>체험 진도 초기화 확인</button></div>';
   el.after(panel);el.hidden=true;
   panel.querySelector('[data-reset-cancel]').addEventListener('click',()=>{panel.remove();el.hidden=false;el.focus();});
   panel.querySelector('[data-reset-confirm]').addEventListener('click',()=>{progress.reset();lastCompleted=-1;resultsUnitId=null;renderMap();focusMain();});
   panel.querySelector('[data-reset-cancel]').focus();panel.scrollIntoView({block:'nearest',behavior:'instant'});return;
  }
  focusMain();if(action==='submit')document.querySelector('.answer-feedback')?.scrollIntoView({block:'nearest',behavior:'instant'});
 }));
}
try {
 const response=await fetch(new URL('./data/lessons.json',import.meta.url));if(!response.ok)throw new Error('Content unavailable');
 const data=await response.json();lessons=Array.isArray(data)?data:data.lessons;
 progress=createProgressStore({lessons});renderMap();
} catch(error) {root.innerHTML='<main class="load-error"><h1>학습 지도를 불러오지 못했어요.</h1><p>서버가 실행 중인지 확인하고 페이지를 새로고침해 주세요.</p><button onclick="location.reload()">다시 불러오기</button></main>';console.error(error);}
